### PR TITLE
Make overdubbing not stop at end of loop

### PR DESCRIPTION
**Pull request by ssj71**
Most loopers don't stop once the loop end is reached allowing you to continuously overdub layer after layer without additional clicks. Some users on the forums were  asking for this feature so I thought I'd try to help out.

Bravo on writing clear, well-commented code BTW!

P.S. I just threw this together. Its not tested and I'm not sure when I'll actually have time on my mod to do any testing. :(

### CODE REVIEW

**Comment by stevie67** [comment]
Hi, in general I like the idea. Thanks! However, it changes the behavior from what it does now. So I would suggest adding a knob which can be used to configure the behavior and enable the new behavior. The default should be the old behavior so that everyone using it already will not see any change - unless they want to.

**Comment by ssj71** [comment]
I've updated it so it should now have the same default behavior, but if they set the "Continuous Dub Mode" parameter it should work the way folks are wanting it to. Let me know what you think.

**Review by stevie67 — APPROVED** [review]

**Comment by stevie67** [comment]
Hi, sorry it took a "bit" for the merge request to happen. Personal reasons... Thanks for this, it improves the loopor a lot.

**Comment by ssj71** [comment]
no worries. I've not had time to work on my projects for quite a while myself. Cheers!

**Pull request merged**
